### ISSUE TITLE
Do you have any examples on how to use the libarary

### ISSUE THREAD

**Issue by artangco** [miguelhasse/Net.Wunderlist#4]
I would like to use your library.  I was able to install in my solution but don't know how to go about authenticating and manipulating the wunderlist lists and tasks.  Any example code you have is greatly appreciated.

Saviz

**Comment by miguelhasse** [comment]
Hi Saviz,
I've replied to your email with a small example. Once I get around to tweaking the file upload pattern, I'll update the readme with samples :)

**Comment by thoxx** [comment]
Some code snippets would be really useful :-)

**Comment by cmlindstrom** [comment]
Please post the small example to the Github - that will at least give us something to start with.  Microsoft announced today the integration of Cortana and Wunderlist.  I'm sure you're going to get loads of questions.  I know for me, if I can use/build on your library, it will save a lot of time integrating with Wunderlist's RESTful interface.  Thx....

**Comment by jbest2015** [comment]
Hello Miguel, can you also send the small sample to my email? thanks so much.

**Comment by cmlindstrom** [comment]
FYI - here's another library in case people are interested: https://github.com/cmlindstrom/Ceptara.Wunderlist

**Comment by michaelosthege** [comment]
I like the design! I was able to figure it out without a sample :)

```csharp
// AccessToken and ClientID come from https://developer.wunderlist.com/apps
ServiceClient client = new ServiceClient(AccessToken, ClientID);
CancellationToken cancelToken = new CancellationToken();
IEnumerable<List> lists = await client.Lists.GetAsync(cancelToken);
```

**Comment by miguelhasse** [comment]
Hi @jbest2015, @cmlindstrom and @thoxx, you can find a basic sample attached here... [Program.cs](https://github.com/miguelhasse/Net.Wunderlist/files/681679/Program.cs.txt)

**Comment by jbest2015** [comment]
Hi miguelhasse, thanks so much. Looks like you made some changes so here is a fixed version.
[Program.cs.txt](https://github.com/miguelhasse/Net.Wunderlist/files/749569/Program.cs.txt)
