### ISSUE TITLE
Nugget package not found

### ISSUE THREAD

**Issue by Hydro8** [miguelhasse/Net.Wunderlist#5]
I can't install this package  on visual studio, nugget can't find it.

Any idea where is the problm ?

**Comment by miguelhasse** [comment]
@Hydro8 the package is still in pre-release, so either use the following console command:

`Install-Package Hasseware.Wunderlist -Pre`

...or select "include prerelease" while browsing in the package manager for solution.

**Comment by Hydro8** [comment]
It work great thank !

Do you know how to output all task inside a list ?

It work ok with all the list but not with tasks inside a list. I tried :

`                    var tasks = await client.Tasks.GetAsync(list.Id, null, cancellationToken);
                        
                    foreach (var task in tasks)
                    {
                        Trace.TraceInformation("Task '{0}'", task.Title);
                     }`

But foreach lists, it doesn't find a task :(

**Comment by miguelhasse** [comment]
@Hydro8 here's sample for traversing the List/Task/Subtask hierarchy:

```
using (var client = new ServiceClient(AccessToken, ClientIdentifier))
{
	foreach (var list in await client.Lists.GetAsync(cancellationToken))
	{
		Trace.TraceInformation("List '{0}'", list.Title);

		// Traverse all root Tasks in the List
		foreach (var task in await client.Tasks.GetAsync(list.Id, null, cancellationToken))
		{
			Trace.TraceInformation("Task '{0}'", task.Title);

			// Traverse all Subtasks of the task
			foreach (var subtask in await client.Subtasks.GetByTaskAsync(task.Id, null, cancellationToken))
			{
				Trace.TraceInformation("Subtask '{0}'", subtask.Title);
			}
		}
		// Traverse all Subtasks in the List
		foreach (var subtask in await client.Subtasks.GetByListAsync(list.Id, null, cancellationToken))
		{
			Trace.TraceInformation("Subtask '{0}'", subtask.Title);
		}
	}
}
```

**Comment by Hydro8** [comment]
I try your code, it's working for list but not for tasks inside list :(

**Comment by miguelhasse** [comment]
@Hydro8 can you share a sample of your test structure (List/Task/Subtask hierarchy)?

**Comment by Hydro8** [comment]
I use it as part as my Home Automation system so OnStart function happen when my "plugin" start and PackageHost.WriteInfo is to write inside my HA log

using Constellation;
using Constellation.Package;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Diagnostics;
using System.Linq;
using System.Net.Wunderlist;
using System.Threading;
using System.Threading.Tasks;

namespace Wunderlist
{
    public class Program : PackageBase
    {
        private const string ClientIdentifier = "hide";
        private const string AccessToken = "hide";

        static void Main(string[] args)
        {
            PackageHost.Start<Program>(args);
        }

        public override void OnStart()
        {
            PackageHost.WriteInfo("Package starting - IsRunning: {0} - IsConnected: {1}", PackageHost.IsRunning, PackageHost.IsConnected);

            Trace.Listeners.Add(new ConsoleTraceListener());
            AppDomain.CurrentDomain.UnhandledException += (s, e) => Trace.TraceError(((Exception)e.ExceptionObject).ToString());

            var cts = new CancellationTokenSource();
            cts.Token.Register(() => Trace.TraceWarning("All operations canceled."));
            
            var sw3 = new Stopwatch();
            sw3.Restart();
            Demo3(cts.Token).ContinueWith(t =>
            {
                sw3.Stop();
                if (t.IsFaulted) Trace.TraceError(t.Exception.GetBaseException().ToString());
                Trace.TraceInformation("Finnished demo 3. [{0}]", sw3.Elapsed);
                PackageHost.WriteInfo("{0}", sw3.Elapsed);
            });

            cts.Cancel();
            Thread.Sleep(5000);
        }

        static async Task Demo3(CancellationToken cancellationToken)
        {
            using (var client = new ServiceClient(AccessToken, ClientIdentifier))
            {
                foreach (var list in await client.Lists.GetAsync(cancellationToken))
                {
                    Trace.TraceInformation("List '{0}'", list.Title);
                    PackageHost.WriteInfo("{0}", list.Title);
                    // Traverse all root Tasks in the List
                    foreach (var task in await client.Tasks.GetAsync(list.Id, null, cancellationToken))
                    {
                        Trace.TraceInformation("Task '{0}'", task.Title);
                        PackageHost.WriteInfo("Task '{0}'", task.Title);
                        // Traverse all Subtasks of the task
                        foreach (var subtask in await client.Subtasks.GetByTaskAsync(task.Id, null, cancellationToken))
                        {
                            Trace.TraceInformation("Subtask '{0}'", subtask.Title);
                            PackageHost.WriteInfo("Subtask '{0}'", subtask.Title);
                        }
                    }
                    // Traverse all Subtasks in the List
                    foreach (var subtask in await client.Subtasks.GetByListAsync(list.Id, null, cancellationToken))
                    {
                        Trace.TraceInformation("Subtask '{0}'", subtask.Title);
                        PackageHost.WriteInfo("Subtask2 '{0}'", subtask.Title);
                    }
                }
            }
        }
    }
}

This is my HA log output 

> [MIDGARD_UI/Wunderlist] 05:43:23 : Package starting - IsRunning: True - IsConnected: True
[MIDGARD_UI/Wunderlist] 05:43:24 : List 'inbox'
[MIDGARD_UI/Wunderlist] 05:43:24 : List 'Grocery'

But no tasks :(

**Comment by Hydro8** [comment]
Hi
This is a repo of my code:

https://github.com/Hydro8/constellation-packages/blob/master/Wunderlist/Wunderlist/Program.cs

Still have lists but no tasks

**Comment by miguelhasse** [comment]
@Hydro8 I have no issue getting tasks for each list. Anyway, I did an update to the pre-release Nuget package, and you should try that before other efforts to solve your issue. This update includes remaining resource access implementation, but I still have to review the large file upload management.

**Comment by jlatimer11** [comment]
Having a small issue using the sample code above.

Using 1.0.0-beta2 the `foreach (var list in await client.Lists.GetAsync(cancellationToken))` line now requires a `uint Id` and I'm not sure what I'm supposed to be supplying there.

Any ideas?

**Comment by miguelhasse** [comment]
@jlatimer11 actually the Lists.GetAsync(...) method can take an Id, but does not require one. If you pass in a null value, all available list entries are returned.

**Comment by jlatimer11** [comment]
That worked fine, but I've found something else I can't quite wrap my head around.

How do I get the accessToken? I'm able to get an Uri from `System.Net.Wunderlist.Authorization.GetAuthorizationEndpoint` and when I enter it in a browser manually I get the state and code, but I can't figure out what to do with the Uri inside C# to get the state and code to pass to `System.Net.Wunderlist.Authorization.TokenExchangeAsync` to get the accessToken.

Any help would be greatly appreciated. I'm fairly new with OAuth.
