### ISSUE TITLE
Problem with Tasks

### ISSUE THREAD

**Issue by Hydro8** [miguelhasse/Net.Wunderlist#6]
Hi
I use your package, it works great !
But I don't achieve to get tasks for each lists, every time the tasks.count = 0.

Here my code : (WriteInfo is to output result to my home automation system)

`            using (var client = new ServiceClient(AccessToken, ClientIdentifier))
            {
                foreach (var list in await client.Lists.GetAsync(cancellationToken))
                {
                    Trace.TraceInformation("List '{0}'", list.Title);
                    PackageHost.WriteInfo(list.Title);
                    // Traverse all root Tasks in the List
                    var tasks = await client.Tasks.GetAsync(list.Id, null, cancellationToken);
                    PackageHost.WriteInfo("{0}",tasks.Count());
                    foreach (var task in await client.Tasks.GetAsync(list.Id, null, cancellationToken))
                    {
                        Trace.TraceInformation("Task '{0}'", task.Title);
                        PackageHost.WriteInfo(task.Title);
                        // Traverse all Subtasks of the task
                        foreach (var subtask in await client.Subtasks.GetByTaskAsync(task.Id, null, cancellationToken))
                        {
                            Trace.TraceInformation("Subtask '{0}'", subtask.Title);
                            PackageHost.WriteInfo(subtask.Title);
                        }
                    }
                    PackageHost.WriteInfo("test");
                    // Traverse all Subtasks in the List
                    foreach (var subtask in await client.Subtasks.GetByListAsync(list.Id, null, cancellationToken))
                    {
                        Trace.TraceInformation("Subtask '{0}'", subtask.Title);
                        PackageHost.WriteInfo(subtask.Title);
                    }
                    PackageHost.WriteInfo("test2");
                }
            }`

And here my home automation system output :

> [MIDGARD_UI/Wunderlist] 08:19:48 : inbox
[MIDGARD_UI/Wunderlist] 08:19:48 : 0
[MIDGARD_UI/Wunderlist] 08:19:48 : test
[MIDGARD_UI/Wunderlist] 08:19:48 : test2
[MIDGARD_UI/Wunderlist] 08:19:48 : Groceries
[MIDGARD_UI/Wunderlist] 08:19:49 : 0
[MIDGARD_UI/Wunderlist] 08:19:49 : test
[MIDGARD_UI/Wunderlist] 08:19:49 : test2

Do you know why it can't detect my tasks inside a list ? Do I need to do something on wunderlist side ?

Thank for your work.

**Comment by miguelhasse** [comment]
@Hydro8 I have no issue getting tasks for each list. Anyway, I did an update to the pre-release Nuget package, and you should try that before other efforts to solve your issue. This update includes remaining resource access implementation, but I still have to review the large file upload management.
